### ISSUE TITLE
C-style declarations might create performance bottlenecks down the line

### ISSUE THREAD

**Issue by flysand7** [Goubermouche/sigma#2]
I'll say it right away that I don't have a personal preference. But seeing the language having goals of moving from LLVM backend to TB and storing tokens and AST in a better data structure, I've come to the conclusion that it concerns itself with compile times somewhat.

## The problem of C-style declarations

C was designed at the time when computers had little memory so that the compilers could compile the whole program in one pass without using too much memory. In current hardware this creates performance bottlenecks since that syntax can not be processed in parallel, by multiple threads. To demonstrate the problem, let's start with the following example.

```
Foo* a;
```

Is this a type declaration or a multiplication? In case the ambiguity is not obvious, let's insert a whitespace and rename all instances of `foo` to lowercase.

```
foo * a;
```

Now it looks more like multiplication.

The parser can not make that distinction without knowing whether `Foo` is a type or a variable. The only way to know that is to look at already-parsed AST and see whether it was declared as a type or not. Which introduces an order-dependency into the parsing. Since that type could have come from a different file (once this compiler is able to support multiple source files in a program), this also introduces an order dependency on files.

At the end your whole program needs to be compiled by a single thread, and the user needs to specify forward declarations to overcome this order dependency.

## Potential solutions

Now, other languages do have C-style declarations, what are they doing to avoid this problem?

- *Java* has a fairly simple type system. If there are two identifiers in a row, that's a declaration. The only things that can be attached to the identifier to the right at the start of the statement are `[]` (arrays) and potentially generic arguments `<T>`, (it uses some contextual lexing to not confuse them with `<` (less-than) and `>` (greater-than) operators, which could make it a bit complicated to parse. Attaching those things to an identifier makes it a type.
- *C#* - I have no idea how they do it, probably they don't have this ambiguity because you can't have a multiply operator in a statement, otherwise it's similar to java.
- *C3* is a language that's quite close to this project in terms of scope (mainly the part about being C-like), so what they do is limit custom typedefs to start from a capital letter, and use `CamelCase` identifiers for custom types. There are a bunch of weird rules, like they consider `A` to be a caps identifier rather than camel case.
- *Go*, *Rust*, *Odin*, *Type Scipt* all chose the Pascal-style declaration syntax. I think that's the easiest approach as it doesn't rely on hidden knowledge about your grammar, the least error prone for tooling, and the easiest to work with.

Now, the question is, what's sigma's take on this?

**Comment by hexratcc** [comment]
Interesting point, up until now I've chosen to use the C-style declarations, which you've rightly pointed out could cause a performance bottleneck. I reckon I'll probably go with something similar to Java, but I haven't implemented custom types yet, as I've been occupied by other parts of the compiler, but I think I'll be doing something like this: 
- Parse individual files, without any 'global' context, which means I can multithread this. My parser will probably fall back to interpreting identifiers in places where there should be a type as a `potential_type` node. 
- After I parse all my files I'll concatenate the generated AST's into one big AST (this might not even be necessary) and I'll throw it into a type checker, which will resolve all potential types and potentially throw errors when needed. 
- Continue with the codegen...

Now again, I'm not entirely sure if this is how I'll be handling things, but it seems quite rational right now, as it allows me to multi thread the Parsing and tokenization processes (I may even be able to multithread the type checker, but I'm not sure if this is viable - think something along the lines of Odin's multithreaded type checker). 

Hope this helps :smile:
